### PR TITLE
User inferface for 802.11g and other fixes / improvements.

### PR DESCRIPTION
**Pull request by dkerr64**
@jgstroud can you take a look at this please.  I have confirmed that setting to 802.11g is working (I can monitor on my Unifi Controller... by default it connects as 802.11n, with this setting it goes to 802.11g).

I have also added some callbacks into the WiFi code so we can monitor connectivity.

This also allows setting device name... but note that if it is already paired, the name in HomeKit / Apple Home will not change.

I have NOT implemented any WiFi recovery / fall back to not forcing 802.11g yet.  I'm not sure how best to do that, but found the callbacks as part of my investigation.  But it may be as simple as setting a ticker to fire after some delay (how long?) and testing WiFi.status() for connected.

### CODE REVIEW

**Comment by jgstroud** [comment]
Nice. I'll review it this evening.  For fallback I was going to do as you suggested and check status in each loop until a 30s timer elapsed.  That said, I'm not sure how much a fallback is needed here.  Do people block 11G on their networks?

**Comment by dkerr64** [comment]
I think it highly unlikely that anyone block 802.11g

I would like to figure out if we can allow for changing SSID / Password in the user interface.  In which case failure to connect is far more likely and a fall back to previously working config would be more useful.  However saving of SSID/Password seems to be buried inside Wifi and Improv setup.  So I have to investigate if doable.

**Comment by jgstroud** [comment]
I just had a thought on this.  In keeping with the original goal of not having configurables, what if we automatically drop to G only if the connection drops for X amount of time.

**Comment by edrikk** [comment]
For what it’s worth, although initially “no configuration” may have been the guiding principle, we have to be cognizant that:
1) The original developer is not maintainer any longer
2) Original vision was no configurables on the main page - which is still the case.  The main page is clean and settings are not in user’s face.
3) There are already items which are configurable (eg v1 or v2)
4) People using ratgdo are (currently) tech savvy.  They have to be comfortable enough to wire it up, serial for initial setup, etc)

If that is agreeable, we can then say that:
- A device becomes much more standalone, “untethered” if basic settings for operation are available for update.
- Breaking that dependency to flashing that exists today to update config is in the base mission of RATGDO.  Don’t depend on anything outside.
- Sane defaults will still allow people to in theory “never” go into the settings page.

**Comment by jgstroud** [comment]
I really don't disagree with any of those comments.

You are correct that the original developer has left the project, and in doing so, I have assumed ownership of the project for the time being.  Just out of respect for what he built, I would like to avoid straying too far from the goals originally set.  You are correct that we have already added config options, but I just want to consider if there is a better way before committing to more.

At the moment, I'm thinking the config option is still the best route for this feature as it eliminates a lot of failure modes and corner cases.  But I wanted to throw the idea out there while it was on my mind.

**Comment by dkerr64** [comment]
I have implemented a check after 30 seconds and if device does not connect it resets the WiFiPhyMode to zero (auto I assume).

However... I have observed on my Unifi Controller that after having set the device to 802.11g it doesn't just go back to 802.11n on rebooting (even after disabling the force to 802.11g).  I am wondering if we need to change the setting to allow for all configurable options... "auto", 802.11b, 802.11g and 802.11n.   This is easy to do (switch from check box to radio button) but should we?

**Comment by dkerr64** [comment]
I updated the user interface to allow selection of any of the possible versions.  What I have observed is that if I select "auto" then it connects to the same version as it was previously... this is probably my Unifi access point remembering what version the device used last time it connected, and so defaulting to that.

I've also observed that selecting 802.11b does not (in my case) force use of 802.11b... my Unifi access points are connecting with 802.11g in this case.  I don't know if this is because my Unifi APs are insisting on that, or because there is something wrong with the ratgdo device or WiFi s/w in it.

**Comment by dkerr64** [comment]
I've been checking 802.11b support by changing settings on my Unifi Controller.  I *think* it is working but it could use additional testing.  The controller is stating that the device connects as "WiFi 3" which is supposed to be equivalent to 802.11g.  However it does show Rx/Tx rate as 11Mbps which is the maximum for 802.11b.  If I change the device to 802.11g then the controller still says WiFi 3 but shows Rx/Tx rate as 54Mbps which is higher than the 'b' standard supported.  So, I think we're good.

Another observation... whenever I change a setting in my Unifi Controller, it may cause a client to disconnect.  The good news is that is working...

```
>>> [50737326] RATGDO: WiFi disconnected SSID: KIoT, Reason: 34
>>> [50737332] HomeKit: [Client 1073698404] Disconnected!
>>> [50737338] HomeKit: [Client 1073698404] Closing client connection
>>> [50738446] RATGDO: WiFi disconnected SSID: KIoT, Reason: 201
>>> [50742401] RATGDO: WiFi disconnected SSID: KIoT, Reason: 2
>>> [50746257] RATGDO: WiFi disconnected SSID: KIoT, Reason: 4
>>> [50749138] RATGDO: WiFi connected SSID: KIoT, Channel: 11
>>> [50749165] RATGDO: WiFi Got IP: 192.168.29.88, Mask: 255.255.255.0, Gateway: 192.168.29.3
>>> [50749174] HomeKit: WiFi connected, ip: 192.168.29.88, mask: 255.255.255.0, gw: 192.168.29.3
>>> [50749183] HomeKit: Configuring MDNS
>>> [50749187] HomeKit: MDNS restart: Garage Door Middle, IP: 192.168.29.88
>>> [50790599] HomeKit: Got new client: local 192.168.29.88:5556, remote 192.168.17.224:53071
>>> [50790608] HomeKit: Setting Timeout to 500ms
>>> [50790613] HomeKit: [Client 1073698404] Pair Verify Step 1/2
>>> [50791115] HomeKit: Free heap: 20520
>>> [50791157] HomeKit: [Client 1073698404] Pair Verify Step 2/2
>>> [50791165] HomeKit: [Client 1073698404] Found pairing with 3AD3752B-B0A1-49F5-8327-044D168639D0
>>> [50791200] HomeKit: [Client 1073698404] Verification successful, secure session established
>>> [50791209] HomeKit: Free heap: 20632
>>> [50791217] HomeKit: [Client 1073698404] Get Accessories
>>> [50791250] RATGDO: get active: 1
>>> [50791255] RATGDO: get current door state: 1
>>> [50791260] RATGDO: get target door state: 1
>>> [50791273] RATGDO: get obstruction: 0
>>> [50791279] RATGDO: get current lock state: 0
>>> [50791284] RATGDO: get target lock state: 0
>>> [50791300] RATGDO: get light state: Off
```

**Comment by jgstroud** [comment]
I haven't had time to really look at this.  Is it ready to merge into the mainline?  Do you need more testing?

**Comment by dkerr64** [comment]
I think we should merge.  Thanks.

**Pull request merged**
